[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    '@aave/core-v3/=lib/aave-v3-core/',
    'aave-helpers/=lib/aave-helpers/src/',
    '@uniswap/v3-core/=lib/v3-core/',
    'solidity-utils/=lib/V2-V3-migration-helpers/lib/solidity-utils/src/'
]
fs_permissions = [
    { access = "read", path = "./out/"},
    { access = "read", path = "./script/input/"},
    { access = "read-write", path = "./script/output/"},
    { access = "write", path = "./reports" }
]
solc_version = '0.8.10'
optimizer = true
optimizer_runs = 100000

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 160
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[rpc_endpoints]
mainnet = "${ETH_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
arbitrum_sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}", chain = 1 }
sepolia = { key = "${ETHERSCAN_API_KEY}", chain = 11155111 }
arbitrum_sepolia = { key = "${API_KEY_ARBISCAN}", chain = 421614, url = "${ARBISCAN_SEPOLIA_URL}" }
gnosis_chain = { key = "${GNOSISSCAN_API_KEY}", chain = 100, url = "https://api.gnosisscan.io/api" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
